# Generated by Django 6.1.1 on 2026-09-25 14:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluator_type', models.CharField(default='COMPOSITE', max_length=50)),
                ('overall_score', models.IntegerField(default=0, help_text='0-100 overall score')),
                ('overall_summary', models.TextField()),
                ('strengths', models.JSONField(default=list, help_text='List of positive findings')),
                ('improvement_areas', models.JSONField(default=list, help_text='List of areas needing work')),
                ('actionable_recommendations', models.JSONField(default=list, help_text='Concrete actionable steps')),
                ('category_scores', models.JSONField(default=dict, help_text='Breakdown by EvaluationCategory')),
                ('raw_ai_response', models.TextField(blank=True, null=True)),
                ('is_fallback', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LLDProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], default='MEDIUM', max_length=20)),
                ('summary', models.TextField(help_text='Short overview for problem cards')),
                ('problem_statement', models.TextField(help_text='Full markdown problem description')),
                ('constraints', models.JSONField(default=list, help_text='List of constraints')),
                ('expected_design_considerations', models.JSONField(default=list, help_text='Design considerations expected from learner')),
                ('hints', models.JSONField(default=list, help_text='Progressive hints')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('requirements_coverage', 'requirements_coverage'), ('responsibility_assignment', 'responsibility_assignment'), ('abstraction_and_interfaces', 'abstraction_and_interfaces'), ('solid_principles', 'solid_principles'), ('coupling_and_cohesion', 'coupling_and_cohesion'), ('extensibility', 'extensibility'), ('design_patterns', 'design_patterns'), ('edge_cases', 'edge_cases'), ('overall_explanation', 'overall_explanation')], max_length=50)),
                ('source', models.CharField(choices=[('DETERMINISTIC', 'DETERMINISTIC'), ('AI_SUGGESTION', 'AI_SUGGESTION')], default='DETERMINISTIC', max_length=30)),
                ('severity', models.CharField(choices=[('POSITIVE', 'POSITIVE'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('CRITICAL', 'CRITICAL')], default='INFO', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(help_text='Detailed explanation of reasoning')),
                ('target_entity', models.CharField(blank=True, max_length=150, null=True)),
                ('suggestion', models.TextField(blank=True, help_text='Concrete suggestion', null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='core.evaluation')),
            ],
            options={
                'ordering': ['category', 'severity'],
            },
        ),
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED', 'SUBMITTED'), ('EVALUATING', 'EVALUATING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='DRAFT', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.lldproblem')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('problem', 'attempt_number')},
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='core.practiceattempt'),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, default='', help_text='High level architecture & flow')),
                ('assumptions_and_tradeoffs', models.TextField(blank=True, default='', help_text='Design trade-offs and assumptions')),
                ('design_patterns_used', models.JSONField(blank=True, default=list)),
                ('mermaid_diagram', models.TextField(blank=True, default='', help_text='Mermaid classDiagram syntax')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='core.practiceattempt')),
            ],
        ),
        migrations.CreateModel(
            name='ClassDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('responsibility', models.TextField(help_text='Single Responsibility explanation')),
                ('attributes', models.JSONField(blank=True, default=list, help_text='[{name, type, visibility}]')),
                ('methods', models.JSONField(blank=True, default=list, help_text='[{name, returnType, params, visibility}]')),
                ('relationships', models.JSONField(blank=True, default=list, help_text='[{target, type, multiplicity, description}]')),
                ('interfaces_implemented', models.JSONField(blank=True, default=list, help_text='List of interface names')),
                ('is_interface', models.BooleanField(default=False)),
                ('is_abstract', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.solution')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProblemRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('req_code', models.CharField(help_text='e.g. REQ-1, REQ-2', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(default='FUNCTIONAL', max_length=50)),
                ('keywords', models.JSONField(default=list, help_text='Keywords/entity names for deterministic checks')),
                ('order', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.lldproblem')),
            ],
            options={
                'ordering': ['order', 'req_code'],
                'unique_together': {('problem', 'req_code')},
            },
        ),
    ]
